name: Feedback
description: General feedback
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
    validations:
      required: true
